-- =============================================================================
-- AgriVision: Supabase PostgreSQL Schema
-- Migration from SQLite (data/products.db & data/rentals.db) to PostgreSQL
-- =============================================================================

-- Enable pgcrypto extension if UUIDs or cryptographic functions are needed
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. Table: products (Module 5: Product Verifier Registry)
-- Source: data/products.db -> products table
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    code          TEXT PRIMARY KEY,
    product_name  TEXT NOT NULL,
    manufacturer  TEXT NOT NULL,
    batch         TEXT,
    expiry        DATE,
    status        TEXT NOT NULL DEFAULT 'Verified',
    product_type  TEXT,
    registered_on TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Index for filtering by status / product_type
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);
CREATE INDEX IF NOT EXISTS idx_products_type ON products(product_type);

-- -----------------------------------------------------------------------------
-- 2. Table: users (Module 7: Equipment Rental Marketplace Users)
-- Source: data/rentals.db -> users table
-- Roles: 'farmer' (books machines) or 'owner' (lists machines)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('farmer', 'owner')),
    full_name     TEXT,
    phone         TEXT,
    location      TEXT,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

-- -----------------------------------------------------------------------------
-- 3. Table: machines (Module 7: Equipment Rental Marketplace Listings)
-- Source: data/rentals.db -> machines table
-- Owner: foreign key to users.id with ON DELETE CASCADE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS machines (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    machine_type TEXT,
    hourly_rate  NUMERIC(10, 2) NOT NULL,
    daily_rate   NUMERIC(10, 2) NOT NULL,
    location     TEXT,
    owner_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    description  TEXT,
    available    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at   TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_machines_owner_id ON machines(owner_id);
CREATE INDEX IF NOT EXISTS idx_machines_type ON machines(machine_type);
CREATE INDEX IF NOT EXISTS idx_machines_available ON machines(available);
CREATE INDEX IF NOT EXISTS idx_machines_location ON machines(location);

-- -----------------------------------------------------------------------------
-- 4. Table: bookings (Module 7: Machine Rental Bookings)
-- Source: data/rentals.db -> bookings table
-- References: machines.id (CASCADE) and users.id (CASCADE)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id  BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
    farmer_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    total_cost  NUMERIC(10, 2),
    status      TEXT NOT NULL DEFAULT 'confirmed',
    notes       TEXT,
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_bookings_machine_id ON bookings(machine_id);
CREATE INDEX IF NOT EXISTS idx_bookings_farmer_id ON bookings(farmer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_dates ON bookings(machine_id, start_date, end_date);

-- -----------------------------------------------------------------------------
-- Helper Views: Replicate joined queries used in modules/equipment_rental.py
-- -----------------------------------------------------------------------------

-- Matches MACHINE_SELECT in modules/equipment_rental.py
CREATE OR REPLACE VIEW view_machine_listings AS
SELECT
    m.id,
    m.name,
    m.machine_type,
    m.hourly_rate,
    m.daily_rate,
    m.location,
    m.owner_id,
    m.description,
    m.available,
    m.created_at,
    m.updated_at,
    u.username AS owner_username,
    u.full_name AS owner_name,
    u.phone AS owner_phone,
    (
        SELECT COUNT(*)
        FROM bookings b
        WHERE b.machine_id = m.id
          AND b.status != 'cancelled'
          AND b.end_date >= CURRENT_DATE
    )::INT AS upcoming_bookings
FROM machines m
JOIN users u ON u.id = m.owner_id;

-- Matches BOOKING_SELECT in modules/equipment_rental.py
CREATE OR REPLACE VIEW view_booking_details AS
SELECT
    b.id,
    b.machine_id,
    b.farmer_id,
    b.start_date,
    b.end_date,
    b.total_cost,
    b.status,
    b.notes,
    b.created_at,
    m.name AS machine_name,
    m.machine_type,
    m.hourly_rate,
    m.daily_rate,
    m.location AS machine_location,
    m.owner_id,
    f.username AS farmer_username,
    f.full_name AS farmer_name,
    f.phone AS farmer_phone
FROM bookings b
JOIN machines m ON m.id = b.machine_id
JOIN users f ON f.id = b.farmer_id;
