"""
training/fine_tune.py
=====================
Lightweight **transfer-learning / fine-tuning** of the pretrained plant-disease
model on the additional Kaggle PlantVillage subset generated by
``training/download_dataset.py``.

Strategy (configurable, CPU / free-Colab friendly)
--------------------------------------------------
1. start from ``models/mobilenetv2_plant.pth`` (already fine-tuned on the
   38-class augmented PlantVillage dataset - we never train from scratch)
2. freeze the whole MobileNetV2 backbone (``model.features``)
3. train the 38-way classifier head with a low learning rate
4. optionally unfreeze the last N feature blocks for a short second phase
   (``--unfreeze-blocks``), still with a low learning rate
5. keep the epoch with the best *validation accuracy* and save it to
   ``models/agrivision_cnn.pth``

The 15-class subset is mapped back into the global 38-class index space (see
``modules.crop_doctor.build_image_folder_dataset``), so the fine-tuned
checkpoint keeps the same output structure as the pretrained one.

Usage
-----
    python training/fine_tune.py
    python training/fine_tune.py --epochs 5 --batch-size 32 --lr 0.001
    python training/fine_tune.py --epochs 8 --unfreeze-blocks 2 --lr 0.0003
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import torch  # noqa: E402
import torch.nn as nn  # noqa: E402
from torch.utils.data import DataLoader  # noqa: E402

from modules.crop_doctor import (  # noqa: E402
    NUM_CLASSES,
    augment_transform,
    build_image_folder_dataset,
    build_model,
    get_device,
    load_checkpoint_into_model,
    preprocess_transform,
)
from utils.helpers import (  # noqa: E402
    DATASET_DIR,
    EVALUATION_DIR,
    FINE_TUNED_MODEL_PATH,
    PRETRAINED_MODEL_PATH,
    ensure_directories,
    load_class_names,
    save_json,
    seed_everything,
    timestamp,
)

def set_backbone_trainable(model: nn.Module, trainable: bool) -> None:
    """Freeze / unfreeze the convolutional backbone (``model.features``)."""
    for parameter in model.features.parameters():
        parameter.requires_grad = trainable

def unfreeze_last_blocks(model: nn.Module, blocks: int) -> int:
    """Unfreeze the last ``blocks`` MobileNetV2 inverted-residual blocks."""
    if blocks <= 0:
        return 0
    inverted_residuals = [layer for layer in model.features if hasattr(layer, "__len__")]
    chosen = inverted_residuals[-blocks:] if blocks <= len(inverted_residuals) else inverted_residuals
    for layer in chosen:
        for parameter in layer.parameters():
            parameter.requires_grad = True
    return len(chosen)

def build_loaders(
    dataset_dir: Path,
    class_names: List[str],
    batch_size: int,
    num_workers: int,
) -> Tuple[DataLoader, DataLoader, Dict[str, Any]]:
    """Create the train/val loaders with the global class-index mapping."""
    train_dir = dataset_dir / "train"
    val_dir = dataset_dir / "val"
    if not train_dir.exists() or not val_dir.exists():
        raise SystemExit(
            f"{dataset_dir} is missing train/ or val/. "
            "Run: python training/download_dataset.py"
        )

    train_dataset = build_image_folder_dataset(
        train_dir, class_names, transform=augment_transform()
    )
    val_dataset = build_image_folder_dataset(
        val_dir, class_names, transform=preprocess_transform()
    )

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers
    )
    val_loader = DataLoader(
        val_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers
    )
    info = {
        "train_images": len(train_dataset),
        "val_images": len(val_dataset),
        "folder_to_global_index": dict(getattr(train_dataset, "class_mapping", {})),
        "train_folders": list(train_dataset.classes),
    }
    return train_loader, val_loader, info

# Training / validation loops

def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> Tuple[float, float]:
    """One epoch of fine-tuning. Returns ``(mean_loss, accuracy)``."""
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for images, targets in loader:
        images = images.to(device)
        targets = targets.to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(images)
        loss = criterion(logits, targets)
        loss.backward()
        optimizer.step()

        running_loss += float(loss.item()) * images.size(0)
        correct += int((logits.argmax(dim=1) == targets).sum().item())
        total += images.size(0)
    return running_loss / max(1, total), correct / max(1, total)

@torch.no_grad()
def evaluate_loader(
    model: nn.Module, loader: DataLoader, criterion: nn.Module, device: torch.device
) -> Tuple[float, float]:
    """Validation pass. Returns ``(mean_loss, accuracy)``."""
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0
    for images, targets in loader:
        images = images.to(device)
        targets = targets.to(device)
        logits = model(images)
        loss = criterion(logits, targets)
        running_loss += float(loss.item()) * images.size(0)
        correct += int((logits.argmax(dim=1) == targets).sum().item())
        total += images.size(0)
    return running_loss / max(1, total), correct / max(1, total)

def run_fine_tuning(
    dataset_dir: Path = DATASET_DIR,
    pretrained_path: Path = PRETRAINED_MODEL_PATH,
    output_path: Path = FINE_TUNED_MODEL_PATH,
    epochs: int = 5,
    batch_size: int = 32,
    learning_rate: float = 1e-3,
    unfreeze_blocks: int = 0,
    unfreeze_epoch: int = 3,
    weight_decay: float = 1e-4,
    num_workers: int = 0,
    seed: int = 42,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Fine-tune the classifier head (and optionally the last backbone blocks).

    Returns a history dictionary with per-epoch train/val loss and accuracy,
    which ``training/evaluate.py`` and the project report both use.
    """
    seed_everything(seed)
    ensure_directories()
    device = get_device()
    class_names = load_class_names()

    if not Path(pretrained_path).exists():
        raise SystemExit(
            f"Pretrained checkpoint not found: {pretrained_path}\n"
            "Run: python training/download_model.py"
        )

    train_loader, val_loader, info = build_loaders(
        Path(dataset_dir), class_names, batch_size, num_workers
    )
    if verbose:
        print(
            f"[data] train={info['train_images']} val={info['val_images']} "
            f"batch={batch_size} classes_mapped={len(info['folder_to_global_index'])}"
        )
        print(f"[data] dataset={dataset_dir}")

    model = build_model(NUM_CLASSES)
    load_checkpoint_into_model(model, Path(pretrained_path))
    model.to(device)

    # Phase 1: everything frozen except the 38-way head.
    set_backbone_trainable(model, False)
    for parameter in model.classifier.parameters():
        parameter.requires_grad = True

    trainable = [p for p in model.parameters() if p.requires_grad]
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(trainable, lr=learning_rate, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.StepLR(
        optimizer, step_size=max(1, epochs // 3), gamma=0.5
    )

    history: Dict[str, List[float]] = {
        "epoch": [], "train_loss": [], "train_accuracy": [],
        "val_loss": [], "val_accuracy": [], "learning_rate": [], "seconds": [],
        "trainable_parameters": [],
    }
    best_accuracy = -1.0
    best_epoch = 0

    if verbose:
        total_params = sum(p.numel() for p in model.parameters())
        print(
            f"[model] device={device.type} | trainable params="
            f"{sum(p.numel() for p in trainable):,} of {total_params:,} | "
            f"epochs={epochs} | lr={learning_rate}"
        )

    for epoch in range(1, epochs + 1):
        # Optional phase 2: unfreeze the last N feature blocks.
        if unfreeze_blocks > 0 and epoch == max(1, unfreeze_epoch):
            unfrozen = unfreeze_last_blocks(model, unfreeze_blocks)
            trainable = [p for p in model.parameters() if p.requires_grad]
            optimizer = torch.optim.Adam(
                trainable, lr=learning_rate * 0.3, weight_decay=weight_decay
            )
            scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.5)
            if verbose:
                print(
                    f"[phase2] epoch {epoch}: unfroze last {unfrozen} backbone block(s), "
                    f"lr={learning_rate * 0.3}"
                )

        started = time.time()
        train_loss, train_accuracy = train_one_epoch(
            model, train_loader, criterion, optimizer, device
        )
        val_loss, val_accuracy = evaluate_loader(model, val_loader, criterion, device)
        scheduler.step()
        elapsed = time.time() - started

        history["epoch"].append(epoch)
        history["train_loss"].append(train_loss)
        history["train_accuracy"].append(train_accuracy)
        history["val_loss"].append(val_loss)
        history["val_accuracy"].append(val_accuracy)
        history["learning_rate"].append(float(optimizer.param_groups[0]["lr"]))
        history["seconds"].append(round(elapsed, 1))
        history["trainable_parameters"].append(
            sum(p.numel() for p in model.parameters() if p.requires_grad)
        )

        if verbose:
            print(
                f"[epoch {epoch}/{epochs}] train_loss={train_loss:.4f} "
                f"train_acc={train_accuracy * 100:5.1f}% | val_loss={val_loss:.4f} "
                f"val_acc={val_accuracy * 100:5.1f}% | {elapsed:5.1f}s"
            )

        if val_accuracy >= best_accuracy:
            best_accuracy = val_accuracy
            best_epoch = epoch
            torch.save(
                {
                    "state_dict": {
                        key: value.cpu() for key, value in model.state_dict().items()
                    },
                    "arch": "mobilenet_v2",
                    "num_classes": NUM_CLASSES,
                    "class_names": list(class_names),
                    "val_accuracy": val_accuracy,
                    "val_loss": val_loss,
                    "epoch": epoch,
                    "epochs_planned": epochs,
                    "batch_size": batch_size,
                    "learning_rate": learning_rate,
                    "unfreeze_blocks": unfreeze_blocks,
                    "baseline_checkpoint": Path(pretrained_path).name,
                    "dataset_dir": str(dataset_dir),
                    "train_images": info["train_images"],
                    "val_images": info["val_images"],
                    "created_at": timestamp(),
                },
                Path(output_path),
            )

    summary = {
        "output_path": str(output_path),
        "pretrained_checkpoint": Path(pretrained_path).name,
        "dataset_dir": str(dataset_dir),
        "epochs": epochs,
        "batch_size": batch_size,
        "learning_rate": learning_rate,
        "weight_decay": weight_decay,
        "unfreeze_blocks": unfreeze_blocks,
        "train_images": info["train_images"],
        "val_images": info["val_images"],
        "device": device.type,
        "best_epoch": best_epoch,
        "best_val_accuracy": best_accuracy,
        "final_val_accuracy": history["val_accuracy"][-1] if history["val_accuracy"] else None,
        "history": history,
        "class_mapping": info["folder_to_global_index"],
        "created_at": timestamp(),
    }
    save_json(summary, EVALUATION_DIR / "fine_tune_history.json")

    if verbose:
        print("\n" + "=" * 62)
        print(f"[done] best val accuracy {best_accuracy * 100:.2f}% at epoch {best_epoch}")
        print(f"[ok] fine-tuned checkpoint -> {output_path}")
        print(f"[ok] history -> {EVALUATION_DIR / 'fine_tune_history.json'}")
    return summary

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Fine-tune the AgriVision plant-disease classifier (transfer learning)."
    )
    parser.add_argument("--dataset", default=str(DATASET_DIR), help="dataset root (train/ val/)")
    parser.add_argument("--pretrained", default=str(PRETRAINED_MODEL_PATH), help="starting checkpoint")
    parser.add_argument("--out", default=str(FINE_TUNED_MODEL_PATH), help="output checkpoint")
    parser.add_argument("--epochs", type=int, default=5, help="number of epochs")
    parser.add_argument("--batch-size", type=int, default=32, help="batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="learning rate for the head")
    parser.add_argument(
        "--unfreeze-blocks", type=int, default=0,
        help="unfreeze the last N backbone blocks in a second phase (0 = head only)",
    )
    parser.add_argument("--unfreeze-epoch", type=int, default=3, help="epoch that starts phase 2")
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--num-workers", type=int, default=0, help="DataLoader workers")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    run_fine_tuning(
        dataset_dir=Path(args.dataset),
        pretrained_path=Path(args.pretrained),
        output_path=Path(args.out),
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.lr,
        unfreeze_blocks=args.unfreeze_blocks,
        unfreeze_epoch=args.unfreeze_epoch,
        weight_decay=args.weight_decay,
        num_workers=args.num_workers,
        seed=args.seed,
    )
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
